import type { Metadata } from "next";
import { TimerProvider } from "@/provider/TimerContext";
import { Toaster } from "sonner";

import "./globals.css";
import { AddressProvider } from "@/provider/AddressContext";
import { AptosConfigProvider } from "@/provider/AptosConfig";

export const metadata: Metadata = {
  title: "Moonmoverz Telegram mini app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AptosConfigProvider>
          <AddressProvider>
            <TimerProvider>
              {children}
              <Toaster position="bottom-left" richColors />
            </TimerProvider>
          </AddressProvider>
        </AptosConfigProvider>
      </body>
    </html>
  );
}
