import type { Metadata } from "next";
import { TimerProvider } from "@/hooks/TimerContext";
import { Toaster } from "sonner";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <TimerProvider>
          {children}
          <Toaster position="bottom-left" richColors />
        </TimerProvider>
      </body>
    </html>
  );
}
